// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnX-On7PpUbxOcMvl_fqfVoLNl-Xh1W-Q',
    appId: '1:128076653918:web:450ef33b7e2b766bcf1bcf',
    messagingSenderId: '128076653918',
    projectId: 'pict-hackathon',
    authDomain: 'pict-hackathon.firebaseapp.com',
    storageBucket: 'pict-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhYMpVL_H_PUYrfKCmwBvtmDPh2PFupU',
    appId: '1:128076653918:android:5d52350325001520cf1bcf',
    messagingSenderId: '128076653918',
    projectId: 'pict-hackathon',
    storageBucket: 'pict-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vFdd9v1BV_07KNpuj1JuqFPijIpwHww',
    appId: '1:128076653918:ios:728a76798c969efdcf1bcf',
    messagingSenderId: '128076653918',
    projectId: 'pict-hackathon',
    storageBucket: 'pict-hackathon.appspot.com',
    iosBundleId: 'com.example.pictFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vFdd9v1BV_07KNpuj1JuqFPijIpwHww',
    appId: '1:128076653918:ios:abbcd41ba64fa6ddcf1bcf',
    messagingSenderId: '128076653918',
    projectId: 'pict-hackathon',
    storageBucket: 'pict-hackathon.appspot.com',
    iosBundleId: 'com.example.pictFrontend.RunnerTests',
  );
}
